apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-gatewayclass.yaml
  - rbac.yaml
  - controlplane.yaml
  - dataplane.yaml
  - dashboard.yaml
  - services-networkpolicy.yaml
  - aiservice-crd.yaml
  - tokenpolicy-crd.yaml
  - wasmplugin-crd.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: aether-gateway-controlplane-config
    namespace: aether-gateway
    files:
      - config.yaml=controlplane-config.yaml
  - name: aether-gateway-dataplane-config
    namespace: aether-gateway
    files:
      - config.yaml=dataplane-config.yaml