{{- if .Values.dataplane.enabled }}
{{- $ns := include "aether-gateway.namespace" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aether-gateway.name" . }}-dataplane-config
  namespace: {{ $ns }}
  labels:
    {{- include "aether-gateway.dataplane.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "aether-gateway.dataplane.configYaml" . | nindent 4 }}
{{- end }}