kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30180
        hostPort: 80
        protocol: TCP
      - containerPort: 30543
        hostPort: 443
        protocol: TCP
      - containerPort: 32080
        hostPort: 8080
        protocol: TCP
      - containerPort: 32090
        hostPort: 8090
        protocol: TCP
      - containerPort: 32443
        hostPort: 8443
        protocol: TCP
      - containerPort: 31883
        hostPort: 8883
        protocol: TCP
      - containerPort: 31300
        hostPort: 5300
        protocol: UDP
