package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"k8s.io/apimachinery/pkg/util/sets"

	"github.com/nantian-gw/gateway/controlplane/internal/gatewayapi"
	gatewayfeatures "sigs.k8s.io/gateway-api/pkg/features"
)

const (
	markdownFormat = "markdown"
	jsonFormat     = "json"
	namesFormat    = "names"
	auditFormat    = "audit"
)

type output struct {
	Count    int      `json:"count"`
	Features []string `json:"features"`
}

type featureAudit struct {
	Declared          []string `json:"declared"`
	UpstreamUnclaimed []string `json:"upstreamUnclaimed"`
	StaleOrUnknown    []string `json:"staleOrUnknown"`
}

func main() {
	format := flag.String("format", markdownFormat, "output format: markdown, json, names, or audit")
	flag.Parse()

	features := gatewayapi.SupportedFeatureNames()
	names := make([]string, 0, len(features))
	for _, feature := range features {
		names = append(names, string(feature))
	}

	switch strings.ToLower(strings.TrimSpace(*format)) {
	case markdownFormat:
		renderMarkdown(os.Stdout, names)
	case jsonFormat:
		if err := json.NewEncoder(os.Stdout).Encode(output{
			Count:    len(names),
			Features: names,
		}); err != nil {
			fmt.Fprintf(os.Stderr, "encode json: %v\n", err)
			os.Exit(1)
		}
	case namesFormat:
		for _, name := range names {
			fmt.Fprintln(os.Stdout, name)
		}
	case auditFormat:
		audit := buildFeatureAudit(upstreamFeatureNames(), features)
		renderAuditMarkdown(os.Stdout, audit)
		if len(audit.StaleOrUnknown) > 0 {
			os.Exit(1)
		}
	default:
		fmt.Fprintf(os.Stderr, "unsupported format %q\n", *format)
		os.Exit(2)
	}
}

func upstreamFeatureNames() sets.Set[gatewayfeatures.FeatureName] {
	out := sets.New[gatewayfeatures.FeatureName]()
	for _, feature := range gatewayfeatures.AllFeatures.UnsortedList() {
		out.Insert(feature.Name)
	}
	for name := range gatewayfeatures.UDPRouteFeatures {
		out.Insert(name)
	}
	return out
}

func buildFeatureAudit(upstream sets.Set[gatewayfeatures.FeatureName], declared []gatewayfeatures.FeatureName) featureAudit {
	declaredSet := sets.New[gatewayfeatures.FeatureName]()
	for _, name := range declared {
		declaredSet.Insert(name)
	}

	return featureAudit{
		Declared:          sortedStringsFromFeatureSet(declaredSet),
		UpstreamUnclaimed: sortedStringsFromFeatureSet(upstream.Difference(declaredSet)),
		StaleOrUnknown:    sortedStringsFromFeatureSet(declaredSet.Difference(upstream)),
	}
}

func sortedStringsFromFeatureSet(items sets.Set[gatewayfeatures.FeatureName]) []string {
	out := make([]string, 0, items.Len())
	for _, item := range items.UnsortedList() {
		out = append(out, string(item))
	}
	sort.Strings(out)
	return out
}

func renderAuditMarkdown(dst io.Writer, audit featureAudit) {
	fmt.Fprintf(dst, "Declared features: `%d`\n\n", len(audit.Declared))
	fmt.Fprintf(dst, "Upstream features not declared by this repository: `%d`\n\n", len(audit.UpstreamUnclaimed))
	for _, name := range audit.UpstreamUnclaimed {
		fmt.Fprintf(dst, "- `%s`\n", name)
	}
	fmt.Fprintln(dst)
	fmt.Fprintf(dst, "Declared features not found upstream: `%d`\n\n", len(audit.StaleOrUnknown))
	for _, name := range audit.StaleOrUnknown {
		fmt.Fprintf(dst, "- `%s`\n", name)
	}
}

func renderMarkdown(dst io.Writer, names []string) {
	fmt.Fprintln(dst, "<!-- BEGIN GENERATED SUPPORTED FEATURES -->")
	fmt.Fprintln(dst, "This section is auto-generated by `scripts/update-gateway-api-support.sh` from `controlplane/internal/gatewayapi/supported_features.go`.")
	fmt.Fprintln(dst, "It shares the same feature set with the following two public declarations, rather than being manually maintained:")
	fmt.Fprintln(dst, "")
	fmt.Fprintln(dst, "- `GatewayClass.status.supportedFeatures`")
	fmt.Fprintln(dst, "- Conformance `SupportedFeatures` when `ALL_FEATURES=true`")
	fmt.Fprintln(dst, "")
	fmt.Fprintf(dst, "Number of features declared by this repository: `%d`\n", len(names))
	fmt.Fprintln(dst, "")
	fmt.Fprintln(dst, "| Feature | GatewayClass.status | Conformance Profile |")
	fmt.Fprintln(dst, "| --- | --- | --- |")
	for _, name := range names {
		fmt.Fprintf(dst, "| `%s` | `Yes` | `Yes` |\n", name)
	}
	fmt.Fprintln(dst, "<!-- END GENERATED SUPPORTED FEATURES -->")
}
