apiVersion: v1
kind: Secret
metadata:
  name: nantian-controlplane-grpc-tls
  namespace: nantian-gw
  labels:
    app.kubernetes.io/name: nantian-gw
    app.kubernetes.io/part-of: nantian-gw
    app.kubernetes.io/component: controlplane
type: Opaque
stringData:
  tls.crt: |
    replace-with-controlplane-server-certificate
  tls.key: |
    replace-with-controlplane-server-private-key
  ca.crt: |
    replace-with-client-ca-bundle
