apiVersion: v1
kind: Secret
metadata:
  name: nantian-gw-dataplane-xds-tls
  namespace: nantian-gw
  labels:
    app.kubernetes.io/name: nantian-gw
    app.kubernetes.io/part-of: nantian-gw
    app.kubernetes.io/component: dataplane
type: Opaque
stringData:
  tls.crt: |
    replace-with-dataplane-client-certificate
  tls.key: |
    replace-with-dataplane-client-private-key
  ca.crt: |
    replace-with-controlplane-ca-bundle
