apiVersion: apps/v1
kind: Deployment
metadata:
  name: nantian-gw-controlplane
  namespace: nantian-gw
spec:
  template:
    spec:
      containers:
        - name: controlplane
          volumeMounts:
            - name: dataplane-admin-auth
              mountPath: /etc/nantian-gw/dataplane-admin-auth
              readOnly: true
      volumes:
        - name: grpc-tls
          secret:
            secretName: nantian-gw-controlplane-grpc-tls
            optional: false
        - name: admin-auth
          secret:
            secretName: nantian-gw-controlplane-admin-auth
            optional: false
        - name: dataplane-admin-auth
          secret:
            secretName: nantian-gw-dataplane-admin-auth
            optional: false
