apiVersion: apps/v1
kind: Deployment
metadata:
  name: aether-gateway-dataplane
  namespace: aether-gateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: aether-gateway-dataplane
              topologyKey: kubernetes.io/hostname
