apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: nantian-controlplane
    newName: ghcr.io/nantian-gw/nantian-controlplane
    newTag: latest
  - name: nantian-dataplane
    newName: ghcr.io/nantian-gw/dataplane
    newTag: latest
  - name: nantian-gw-dashboard
    newName: ghcr.io/nantian-gw/dashboard
    newTag: latest

patches:
  - path: dataplane-replicas.yaml
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: nantian-gw-controlplane-config
    namespace: nantian-gw
    behavior: replace
    files:
      - config.yaml=controlplane-config.yaml
  - name: nantian-gw-dataplane-config
    namespace: nantian-gw
    behavior: replace
    files:
      - config.yaml=dataplane-config.yaml
